version: 2.1
orbs:
  node: circleci/node@5.2

jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      # - node/install-packages
      - run:
          command: npm run ci:test
      - run:
          command: npm run ci:lint
      - store_test_results:
          path: results.xml 
workflows:
  test_my_app:
    jobs:
      - test
