version: 2.1
orbs:
  node: circleci/node@5.2

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: npm run ci:test
      - run: npm run ci:lint
      - store_test_results:
          path: results.xml
workflows:
  test_my_app:
    jobs:
      - test
