version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:1.16
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "build project"
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
