version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:21.7.2
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm run ci:lint
      - run: npm run ci:test
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: junit.xml
          
  build:
    docker:
      - image: cimg/node:21.7.2
    steps:
      - checkout
      - run: echo "build project"
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test

