name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: node-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run ATS
        uses: codecov/codecov-ats@v0
        env:
          CODECOV_STATIC_TOKEN: ${{ secrets.CODECOV_STATIC_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
      - name: Run tests and collect coverage
        run: npm run test -- ${{ env.CODECOV_ATS_TESTS }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: smart-tests
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tuomashatakka/tuohinen